version: 0.2

env:
  variables:
    PACKAGE: "github.com/csvikram/hello-world-golang"

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p /go/src/github.com/csvikram
      - ln -s ${CODEBUILD_SRC_DIR} "/go/src/${PACKAGE}"

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env


  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/github.com/csvikram/hello-world-golang"

      # Check the Go code for common problems with 'go vet'
      - go vet .

      # Run all tests included with our application
      - go test ./...

  build:
    commands:

      # Build our go application
      - GOOS=linux go build -o main main.go

artifacts:
  type: zip
  base-directory: /go/src/$PACKAGE
  files:
    - main