version: 0.2

env:
  variables:
    PACKAGE: "github.com/csvikram/hello-world-golang"

phases:

  install:
    commands:

      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our
      # application source code into that directory structure.
      - mkdir -p /go/src/github.com/csvikram
      - ln -s ${CODEBUILD_SRC_DIR} "/go/src/${PACKAGE}"

      - npm install newman --global

      # Print all environment variables (handy for AWS CodeBuild logs)
      - env


  pre_build:
    commands:

      # Make sure we're in the project directory within our GOPATH
      - cd "/go/src/github.com/csvikram/hello-world-golang"

      # Check the Go code for common problems with 'go vet'
      - go vet .

      # Run all tests included with our application
      - go test ./...

  build:
    commands:

#      - newman run https://api.getpostman.com/collections/9482a236235874adeb08 --environment localhost8080.json

      # Build our go application
      - GOOS=linux go build -o main main.go
      - go run main.go &

      - newman run -r html,cli https://api.getpostman.com/collections/9482a236235874adeb08 --environment localhost8080.json --reporter-html-export report.html
      - pkill -f "go run main.go"


artifacts:
  type: zip
  base-directory: /go/src/$PACKAGE
  files:
    - main
    - report.html
